name: icidasset-template
version: 2.0.0
maintainer: Steven Vandevelde <icid.asset@gmail.com>


dependencies:
  - aeson == 1.0.*
  - base >= 4.7 && < 5
  - binary == 0.8.*
  - bytestring == 0.10.*
  - cmark == 0.5.*
  - directory == 1.3.*
  - flow == 1.*
  - frontmatter == 0.1.*
  - http-types == 0.9.*
  - lucid == 2.9.*
  - shikensu == 0.3.*
  - text == 1.*
  - unordered-containers == 0.2.*
  - wai == 3.2.*
  - wai-app-static == 3.1.*
  - yaml == 0.8.*


default-extensions:
  - ExtendedDefaultRules
  - OverloadedStrings


library:
  source-dirs:
    haskell
  exposed-modules:
    - Attributes
    - Components.Blocks.Filler
    - Components.Header
    - Components.Icon
    - Components.LoadingScreen
    - Components.LoadingScreenScript
    - Elements
    - Layouts.Application
    - Layouts.Writing
    - Renderers.Lucid
    - Renderers.Markdown
    - Server
    - Shikensu.Functions
    - Template
    - Types
    - Utilities
