name: icidasset-template
version: 1.0.0


dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - cmark
  - flow
  - frontmatter
  - lucid
  - protolude
  - record-hasfield
  - shikensu
  - text
  - unordered-containers
  - yaml


default-extensions:
  - ExtendedDefaultRules
  - NoImplicitPrelude
  - OverloadedStrings


library:
  source-dirs:
    Haskell
